version: "3.1"

services:
    mongo:
        image: mongo:7.0.2
        restart: always
        ports:
            - ${DB_PORT}:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${ROOT_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PASSWORD}

    mongo-express:
        image: mongo-express:1.0.0
        restart: always
        ports:
            - ${EXPRESS_PORT}:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${ROOT_USER}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${ROOT_PASSWORD}
            ME_CONFIG_MONGODB_URL: ${MONGO_EXPRESS_SERVER_CONNECTION_STRING}

    innai-server:
        image: ghcr.io/bauerjakob/innai:server-${INNAI_VERSION}
        ports:
            - 8080:80
        links:
            - mongo
        environment:
            ConnectionStrings__MongoDb: ${INNAI_SERVER_CONNECTION_STRING}
