version: "3.1"

services:
    innai-website:
        image: ghcr.io/bauerjakob/innai-predict:website-${INNAI_VERSION}
        restart: always
        environment:
            - PREDICT_SERVER_BASE_URL=http://innai-server:8080/api/V1
        networks:
            - proxynet
            - frontend

    innai-server:
        image: ghcr.io/bauerjakob/innai-predict:server-${INNAI_VERSION}
        restart: always
        ports:
            - 8000:8080
        environment:
            ConnectionStrings__DefaultConnection: ${INNAI_SERVER_CONNECTION_STRING}
            ApiClients__InnAiPredictionClient__BaseUrl: http://innai-predict:8000
            ApiClients__PrecipitationMapClient__ApiKey: ${OPEN_WEATHER_API_KEY}
        depends_on:
            innai-db:
                condition: service_healthy
        networks:
            - backend
            - frontend

    innai-db:
        image: postgres:${PSQL_TAG}
        restart: always
        ports:
            - 5432:5432
        volumes:
            - ./mount/psql:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${PSQL_USER}
            POSTGRES_PASSWORD: ${PSQL_PASSWORD}
            POSTGRES_DB: ${PSQL_DATABASE}
        healthcheck:
            test:
                ["CMD-SHELL", "pg_isready -U ${PSQL_USER} -d ${PSQL_DATABASE}"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - backend

    innai-predict:
        image: ghcr.io/bauerjakob/innai-predict:predict-${INNAI_VERSION}
        restart: always
        ports:
            - 8000:8000
        networks:
            - backend

networks:
    frontend:
    backend:
    proxynet:
        # external: true
        name: proxynet
